# Generated by Django 5.1.5 on 2025-02-01 05:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(blank=True, default='No answer available', help_text='Enter your answer in English'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(default='No Question available', help_text='Enter your question in English'),
        ),
        migrations.AddField(
            model_name='faq',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
