# Generated by Django 5.1.5 on 2025-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='is_updated',
            field=models.BooleanField(default=True, help_text='Flag indicating if the FAQ content has been updated'),
        ),
    ]
