version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bharath_fd_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bharath_fd
    restart: always  
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
  redis:
    image: "redis"
    ports:
      - "6379:6379"    
    volumes:
      - redis_data:/data  

volumes:
  db_data:
  redis_data:
