version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bharath_fd_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bharath_fd
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
            gunicorn faq_service.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis"
    ports:
      - "6379:6379"    
    volumes:
      - redis_data:/data  

volumes:
  db_data:
  redis_data:
